Update pwd.yml

diff --git a/pwd.yml b/pwd.yml
--- a/pwd.yml
+++ b/pwd.yml
@@ -1,10 +1,10 @@
-version: "3"
+#version: "3.8"
 
 services:
   backend:
     image: frappe/erpnext:v15.70.0
     networks:
-      - frappe_network
+      - frappe_overlay
     deploy:
       restart_policy:
         condition: on-failure
@@ -20,22 +20,19 @@ services:
   configurator:
     image: frappe/erpnext:v15.70.0
     networks:
-      - frappe_network
+      - frappe_overlay
     deploy:
       restart_policy:
         condition: none
-    entrypoint:
-      - bash
-      - -c
-    command:
-      - >
-        ls -1 apps > sites/apps.txt;
-        bench set-config -g db_host $$DB_HOST;
-        bench set-config -gp db_port $$DB_PORT;
-        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
-        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
-        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
-        bench set-config -gp socketio_port $$SOCKETIO_PORT;
+    entrypoint: ["bash", "-c"]
+    command: >
+      ls -1 apps > sites/apps.txt;
+      bench set-config -g db_host $$DB_HOST;
+      bench set-config -gp db_port $$DB_PORT;
+      bench set-config -g redis_cache "redis://$$REDIS_CACHE";
+      bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
+      bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
+      bench set-config -gp socketio_port $$SOCKETIO_PORT;
     environment:
       DB_HOST: db
       DB_PORT: "3306"
@@ -49,40 +46,37 @@ services:
   create-site:
     image: frappe/erpnext:v15.70.0
     networks:
-      - frappe_network
+      - frappe_overlay
     deploy:
       restart_policy:
         condition: none
+    entrypoint: ["bash", "-c"]
+    command: >
+      wait-for-it -t 120 db:3306;
+      wait-for-it -t 120 redis-cache:6379;
+      wait-for-it -t 120 redis-queue:6379;
+      export start=`date +%s`;
+      until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] &&
+            [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] &&
+            [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+      do
+        echo "Waiting for sites/common_site_config.json to be created";
+        sleep 5;
+        if (( `date +%s`-start > 120 )); then
+          echo "could not find sites/common_site_config.json with required keys";
+          exit 1
+        fi
+      done;
+      echo "sites/common_site_config.json found";
+      bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend;
     volumes:
       - sites:/home/frappe/frappe-bench/sites
       - logs:/home/frappe/frappe-bench/logs
-    entrypoint:
-      - bash
-      - -c
-    command:
-      - >
-        wait-for-it -t 120 db:3306;
-        wait-for-it -t 120 redis-cache:6379;
-        wait-for-it -t 120 redis-queue:6379;
-        export start=`date +%s`;
-        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
-          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
-          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
-        do
-          echo "Waiting for sites/common_site_config.json to be created";
-          sleep 5;
-          if (( `date +%s`-start > 120 )); then
-            echo "could not find sites/common_site_config.json with required keys";
-            exit 1
-          fi
-        done;
-        echo "sites/common_site_config.json found";
-        bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend;
 
   db:
     image: mariadb:10.6
     networks:
-      - frappe_network
+      - frappe_overlay
     healthcheck:
       test: mysqladmin ping -h localhost --password=admin
       interval: 1s
@@ -94,7 +88,7 @@ services:
       - --character-set-server=utf8mb4
       - --collation-server=utf8mb4_unicode_ci
       - --skip-character-set-client-handshake
-      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
+      - --skip-innodb-read-only-compressed
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MARIADB_ROOT_PASSWORD: admin
@@ -104,7 +98,7 @@ services:
   frontend:
     image: frappe/erpnext:v15.70.0
     networks:
-      - frappe_network
+      - frappe_overlay
     depends_on:
       - websocket
     deploy:
@@ -121,24 +115,20 @@ services:
       UPSTREAM_REAL_IP_RECURSIVE: "off"
       PROXY_READ_TIMEOUT: 120
       CLIENT_MAX_BODY_SIZE: 50m
+    ports:
+      - "8080:8080"
     volumes:
       - sites:/home/frappe/frappe-bench/sites
       - logs:/home/frappe/frappe-bench/logs
-    ports:
-      - "8080:8080"
 
   queue-long:
     image: frappe/erpnext:v15.70.0
     networks:
-      - frappe_network
+      - frappe_overlay
     deploy:
       restart_policy:
         condition: on-failure
-    command:
-      - bench
-      - worker
-      - --queue
-      - long,default,short
+    command: ["bench", "worker", "--queue", "long,default,short"]
     volumes:
       - sites:/home/frappe/frappe-bench/sites
       - logs:/home/frappe/frappe-bench/logs
@@ -146,15 +136,11 @@ services:
   queue-short:
     image: frappe/erpnext:v15.70.0
     networks:
-      - frappe_network
+      - frappe_overlay
     deploy:
       restart_policy:
         condition: on-failure
-    command:
-      - bench
-      - worker
-      - --queue
-      - short,default
+    command: ["bench", "worker", "--queue", "short,default"]
     volumes:
       - sites:/home/frappe/frappe-bench/sites
       - logs:/home/frappe/frappe-bench/logs
@@ -162,7 +148,7 @@ services:
   redis-queue:
     image: redis:6.2-alpine
     networks:
-      - frappe_network
+      - frappe_overlay
     deploy:
       restart_policy:
         condition: on-failure
@@ -172,7 +158,7 @@ services:
   redis-cache:
     image: redis:6.2-alpine
     networks:
-      - frappe_network
+      - frappe_overlay
     deploy:
       restart_policy:
         condition: on-failure
@@ -180,13 +166,11 @@ services:
   scheduler:
     image: frappe/erpnext:v15.70.0
     networks:
-      - frappe_network
+      - frappe_overlay
     deploy:
       restart_policy:
         condition: on-failure
-    command:
-      - bench
-      - schedule
+    command: ["bench", "schedule"]
     volumes:
       - sites:/home/frappe/frappe-bench/sites
       - logs:/home/frappe/frappe-bench/logs
@@ -194,13 +178,11 @@ services:
   websocket:
     image: frappe/erpnext:v15.70.0
     networks:
-      - frappe_network
+      - frappe_overlay
     deploy:
       restart_policy:
         condition: on-failure
-    command:
-      - node
-      - /home/frappe/frappe-bench/apps/frappe/socketio.js
+    command: ["node", "/home/frappe/frappe-bench/apps/frappe/socketio.js"]
     volumes:
       - sites:/home/frappe/frappe-bench/sites
       - logs:/home/frappe/frappe-bench/logs
@@ -212,5 +194,6 @@ volumes:
   logs:
 
 networks:
-  frappe_network:
-    driver: bridge
+  frappe_overlay:
+    driver: overlay
+    attachable: true
